services:
  postgres_db:
    image: postgres:18-alpine 
    container_name: pixledger_db
    environment:
      POSTGRES_USER: pixledger
      POSTGRES_PASSWORD: pixledger
      POSTGRES_DB: pixledger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pixledger-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pixledger_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    restart: unless-stopped
    networks:
      - pixledger-network

  redis:
    image: redis:8.4.0-alpine
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - pixledger-network

  seq:
    image: datalust/seq:latest
    container_name: pixledger-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
    ports:
      - "5341:80"
    networks:
      - pixledger-network
    restart: unless-stopped

  api:
    image: pixledger-api
    container_name: pixledger-api
    build:
      context: .
      dockerfile: src/PixLedger.Api/Dockerfile
    profiles: ["app"]
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=pixledger_db;Username=pixledger;Password=pixledger;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres_db
    networks:
      - pixledger-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  pixledger-network:
    driver: bridge
  